name: reusable
on:
  workflow_call:
    secrets:
      DEPLOY_TOKEN:
        required: true
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: make deploy
