name: reusable
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      dry_run:
        type: boolean
        required: false
        default: false
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy
        run: echo "deploy ${{ inputs.environment }}"
