#!/bin/bash
# Print the Homebrew formula for a published zghalint release.
#
# Usage: gen-homebrew-formula.sh <tag> <sha256sums-file>
#
# The formula is a bottle-less binary formula: it points at the release
# archives this repository publishes and carries the checksums from the
# release's own SHA256SUMS, so `brew install` verifies exactly what
# `install.sh` and the composite action verify. `release.yml` writes the
# result to watany-dev/homebrew-tap; see docs/maintenance.md.
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: gen-homebrew-formula.sh <tag> <sha256sums-file>" >&2
  exit 2
fi

TAG=$1
SUMS=$2
VERSION=${TAG#v}
REPO=watany-dev/zghalint
BASE_URL="https://github.com/$REPO/releases/download/$TAG"

# A missing entry exits non-zero, which errexit turns into a failed run rather
# than a formula carrying an empty sha256.
sha_for() {
  awk -v name="$1" '
    $2 == name || $2 == "*" name { print $1; found = 1 }
    END { if (!found) { print "gen-homebrew-formula: no entry for " name > "/dev/stderr"; exit 1 } }
  ' "$SUMS"
}

MACOS_AARCH64=$(sha_for "zghalint-macos-aarch64.tar.gz")
MACOS_X86_64=$(sha_for "zghalint-macos-x86_64.tar.gz")
LINUX_AARCH64=$(sha_for "zghalint-linux-aarch64.tar.gz")
LINUX_X86_64=$(sha_for "zghalint-linux-x86_64.tar.gz")

cat <<EOF
# Generated by scripts/gen-homebrew-formula.sh in $REPO.
# Edits made here are overwritten by the next release.
class Zghalint < Formula
  desc "Fast, comprehensive GitHub Actions workflow linter"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$BASE_URL/zghalint-macos-aarch64.tar.gz"
      sha256 "$MACOS_AARCH64"
    end
    on_intel do
      url "$BASE_URL/zghalint-macos-x86_64.tar.gz"
      sha256 "$MACOS_X86_64"
    end
  end

  on_linux do
    on_arm do
      url "$BASE_URL/zghalint-linux-aarch64.tar.gz"
      sha256 "$LINUX_AARCH64"
    end
    on_intel do
      url "$BASE_URL/zghalint-linux-x86_64.tar.gz"
      sha256 "$LINUX_X86_64"
    end
  end

  def install
    # Every archive unpacks into a single zghalint-<os>-<arch>/ directory, which
    # Homebrew strips when staging, leaving the binary at the root. The glob is
    # the fallback for a staging that keeps the directory.
    binary = Dir["zghalint-*/zghalint"].first || "zghalint"
    bin.install binary => "zghalint"
  end

  test do
    assert_match "zghalint v#{version}", shell_output("#{bin}/zghalint --version")

    (testpath/"workflow.yml").write <<~YAML
      name: ci
      on:
        push:
          branches: [main]
      permissions:
        contents: read
      jobs:
        build:
          runs-on: ubuntu-latest
          timeout-minutes: 30
          steps:
            - name: Greet
              run: echo hello
    YAML
    system bin/"zghalint", "--offline", "--", testpath/"workflow.yml"
  end
end
EOF
