#!/usr/bin/env python3
"""Generate docs/schema/zghalint.schema.json from the key tables in config.zig.

The property names come from `schema_*_keys` in src/config.zig. Types and
enums stay here so the JSON Schema can be richer than the Zig arrays; adding
a key to Zig without a type here fails at generate time.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_ZIG = ROOT / "src" / "config.zig"
WORKSPACE_ZIG = ROOT / "src" / "workspace.zig"


def zig_str_array(text: str, name: str) -> list[str]:
    match = re.search(
        rf"pub const {re.escape(name)} = \[_]\[\]const u8\{{(.*?)\}}",
        text,
        re.S,
    )
    if not match:
        raise SystemExit(f"missing {name} in config.zig")
    return re.findall(r'"([^"]+)"', match.group(1))


def zig_enum_fields(text: str, name: str) -> list[str]:
    match = re.search(rf"pub const {re.escape(name)} = enum \{{(.*?)\}}", text, re.S)
    if not match:
        raise SystemExit(f"missing enum {name}")
    fields = []
    for raw in match.group(1).splitlines():
        line = raw.split("//", 1)[0].strip().rstrip(",")
        if not line:
            continue
        fields.append(line.strip("@").strip('"'))
    return fields


def main() -> int:
    config_text = CONFIG_ZIG.read_text()
    workspace_text = WORKSPACE_ZIG.read_text()
    root_keys = zig_str_array(config_text, "schema_root_keys")
    rule_keys = zig_str_array(config_text, "schema_rule_keys")
    output_keys = zig_str_array(config_text, "schema_output_keys")
    runner_keys = zig_str_array(config_text, "schema_runner_keys")

    formats = zig_enum_fields(config_text, "OutputFormat")
    colors = zig_enum_fields(config_text, "ColorMode")
    visibilities = zig_enum_fields(config_text, "Visibility")
    node_caches = zig_enum_fields(workspace_text, "NodeCache")
    python_caches = zig_enum_fields(workspace_text, "PythonCache")

    rule_types = {
        "severity": {"type": "string", "enum": ["error", "warning", "info", "hint"]},
        "enabled": {"type": "boolean"},
        "exclude": {"type": "array", "items": {"type": "string"}},
        "node_cache_manager": {"type": "string", "enum": node_caches},
        "python_cache_manager": {"type": "string", "enum": python_caches},
    }
    output_types = {
        "format": {"type": "string", "enum": formats},
        "color": {"type": "string", "enum": colors},
    }
    runner_types = {
        "labels": {"type": "array", "items": {"type": "string"}},
    }
    root_types = {
        "rules": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": False,
                "properties": {key: rule_types[key] for key in rule_keys},
            },
        },
        "ignore": {"type": "array", "items": {"type": "string"}},
        "runner": {
            "type": "object",
            "additionalProperties": False,
            "properties": {key: runner_types[key] for key in runner_keys},
        },
        "output": {
            "type": "object",
            "additionalProperties": False,
            "properties": {key: output_types[key] for key in output_keys},
        },
        "repo_visibility": {"type": "string", "enum": visibilities},
    }

    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://github.com/watany-dev/zghalint/blob/main/docs/schema/zghalint.schema.json",
        "title": "zghalint configuration",
        "description": (
            "Schema for .zghalint.yml. Generated by scripts/gen-config-schema.py "
            "from src/config.zig."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {key: root_types[key] for key in root_keys},
    }
    json.dump(schema, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
